version: "3.8"

services:
  learningdb:
    container_name: learningdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learning
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_learning:/var/lib/postgresql/data/ 
    networks:
      - learningapp-network   
  
  usersdb:
      container_name: usersdb
      image: postgres:16
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=users
      restart: always
      ports:
          - "5433:5432"
      volumes:
        - postgres_users:/var/lib/postgresql/data/ 
      networks:
        - learningapp-network   
  
  users.api:
    image: user.api
    build:
      context: ../
      dockerfile: src/Services/Auth/Auth.API/Dockerfile
    environment:
      - JwtOptions__SecretKey=qwertyuiopasdfghjklzxcbnmabcdefjhijklmnop
      - JwtOptions__Issue=issuer
      - JwtOptions__Audience=audience
      - JwtOptions__AccessTokenExpirationMinutes=30
      - JwtOptions__RefreshTokenExpirationDays=7
      - ConnectionStrings__UsersDbContext=Host=usersdb;Port=5432;Database=users;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    ports:
      - "8081:8080"
    volumes:
      - ./.aspnet/users.api/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    networks:
      - learningapp-network
    depends_on:
      - rabbitmq
      - usersdb

  learning.api:
    image: learning.api
    build:
      context: ../
      dockerfile: src/Services/Learning/Learning.API/Dockerfile
    environment:
      - RabbitMqSettings__Host=rabbitmq://rabbitmq
      - RabbitMqSettings__Password=guest
      - RabbitMqSettings__UserName=guest
      - JwtOptions__SecretKey=qwertyuiopasdfghjklzxcbnmabcdefjhijklmnop
      - JwtOptions__Issue=issuer
      - JwtOptions__Audience=audience
      - JwtOptions__AccessTokenExpirationMinutes=30
      - JwtOptions__RefreshTokenExpirationDays=7
      - ConnectionStrings__LearningDbContext=Host=learningdb;Port=5432;Database=learning;Username=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Development
      - MinioSettings__Host=minio:9000
      - MinioSettings__ExtHost=localhost:9000
      - MinioSettings__UserName=minio
      - MinioSettings__Password=minio123
    restart: on-failure
    ports:
      - "8082:8080"
    volumes:
      - ./.aspnet/learning.api/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    networks:
      - learningapp-network
    depends_on:
      - learningdb
      - minio
      - rabbitmq

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9002:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio-storage:/data
    networks:
      - learningapp-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - learningdb
    networks:
      - learningapp-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - learningapp-network

networks:
  learningapp-network:

volumes:
  postgres_learning:
  minio-storage:
  rabbitmq:
  postgres_users: